version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: secretos
      POSTGRES_PASSWORD: secretos
      POSTGRES_DB: spc
    ports:
      - "5432:5432"
    volumes:
      - spcdata:/var/lib/postgresql/data

volumes:
  spcdata: